package com.video.test.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.video.test.javabean.CountryCodeBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COUNTRY_CODE_BEAN".
*/
public class CountryCodeBeanDao extends AbstractDao<CountryCodeBean, Long> {

    public static final String TABLENAME = "COUNTRY_CODE_BEAN";

    /**
     * Properties of entity CountryCodeBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CountryCode = new Property(1, int.class, "countryCode", false, "COUNTRY_CODE");
        public final static Property Country = new Property(2, String.class, "country", false, "COUNTRY");
        public final static Property DisplayCode = new Property(3, String.class, "displayCode", false, "DISPLAY_CODE");
    }


    public CountryCodeBeanDao(DaoConfig config) {
        super(config);
    }
    
    public CountryCodeBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COUNTRY_CODE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"COUNTRY_CODE\" INTEGER NOT NULL UNIQUE ," + // 1: countryCode
                "\"COUNTRY\" TEXT NOT NULL UNIQUE ," + // 2: country
                "\"DISPLAY_CODE\" TEXT NOT NULL UNIQUE );"); // 3: displayCode
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COUNTRY_CODE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CountryCodeBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCountryCode());
        stmt.bindString(3, entity.getCountry());
        stmt.bindString(4, entity.getDisplayCode());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CountryCodeBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCountryCode());
        stmt.bindString(3, entity.getCountry());
        stmt.bindString(4, entity.getDisplayCode());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CountryCodeBean readEntity(Cursor cursor, int offset) {
        CountryCodeBean entity = new CountryCodeBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // countryCode
            cursor.getString(offset + 2), // country
            cursor.getString(offset + 3) // displayCode
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CountryCodeBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCountryCode(cursor.getInt(offset + 1));
        entity.setCountry(cursor.getString(offset + 2));
        entity.setDisplayCode(cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CountryCodeBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CountryCodeBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CountryCodeBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
